CREATE TABLE @SCHEMA.`c_user_roles` (
  `EMAIL` varchar(256) NOT NULL,
  `ROLE` varchar(45) DEFAULT NULL,
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`(256), `ROLE`(45))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

