CREATE OR REPLACE VIEW @SCHEMA.`r_questionnaire_info_region` AS
    SELECT 
        `b`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO AS `region`,
        `b`.`total` AS `total`,
        `avg_individual`.`avg_individual` AS `avg_individual`
    FROM
        (((SELECT 
            @SCHEMA.@QUESTIONNAIRE_TABLE.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO AS @QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO,
                COUNT(0) AS `total`
        FROM
            @SCHEMA.@QUESTIONNAIRE_TABLE
        GROUP BY @SCHEMA.@QUESTIONNAIRE_TABLE.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO)) `b`
        JOIN (SELECT 
            `a`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO AS @QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO, AVG(`a`.`num`) AS `avg_individual`
        FROM
            (SELECT 
            `q`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO AS @QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO, COUNT(0) AS `num`
        FROM
            (@SCHEMA.@INDIVIDUAL_TABLE `h`
        JOIN @SCHEMA.@QUESTIONNAIRE_TABLE `q` ON ((`h`.@QUESTIONNAIRE_COLUMN_BASE = `q`.`ID`)))
        GROUP BY `q`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO , `h`.@QUESTIONNAIRE_COLUMN_BASE) `a`
        GROUP BY `a`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO) `avg_individual` ON ((`b`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO = `avg_individual`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO)))
    GROUP BY `b`.@QUESTIONNAIRE_COLUMN_FIRST_LEVEL_GEO;
